### ISSUE TITLE
Missing Font Awesome library

### ISSUE THREAD

**Issue by laijoann** [keyholeco/keychain#3]
### Summary
Missing icons because Font Awesome library is missing from page.

### Relevant Pages
- https://keyholeco.github.io/keychain/?path=/story/atoms-profilepicture--with-url
- https://keyholeco.github.io/keychain/?path=/story/atoms-profilepicture--no-url

### Screenshots
![ProfilePicture (no URL) story](https://user-images.githubusercontent.com/14142540/55827696-c1a89f00-5ad8-11e9-95aa-66a7bcaf4682.png)
![ProfilePicture (with URL) story](https://user-images.githubusercontent.com/14142540/55827703-c705e980-5ad8-11e9-89e9-f77ac6d84b77.png)

**Comment by superhussain** [comment]
Fixed with #8
